site_name: fractrade.xyz
site_description: "Documentation for the fractrade.xyz platform."
site_url: https://fractrade-xyz.github.io/fractrade-docs/
theme:
  name: terminal
  palette: 'dark'
  custom_dir: fractrade_theme
  features:
    - content.code.copy      # Add copy button to code blocks
  
extra_css:
  - stylesheets/extra.css    # Add custom CSS

docs_dir: docs  # Location of the documentation files
use_directory_urls: false  # Add this line
nav:
  - Home: index.md
  - Core Architecture: architecture.md
  - Components:
      - Execution Client: components/client.md
      - Strategy: components/strategy.md
      - Publisher: components/publisher.md
      - Hyperliquid SDK: components/hyperliquid_sdk.md
      - Telegram Bot: components/telegram_bot.md
  - Agent Strategies: 
      - Demo Trader V1: examples/demotraderv1.md
  - Whitepaper: whitepaper.md
  - FRAC Score: fracscore.md
  - FAQ: faq.md
  - Contact: contact.md
